version: '3.8'

services:
  api:
    build: .
    container_name: ecommerce_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - db
      - redis
    networks:
      - ecommerce-network

  db:
    image: postgres:15
    container_name: ecommerce_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network

  redis:
    image: redis:7
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  postgres_data:
  redis_data:
